os-dev:
  module: "src.server.tasks.os_interaction.OSInteraction"
  parameters:
    name: "os-dev"
    concurrency: 24
    round_limit: 8

    docker_config:
      localhost: local-os
      directory: .local/envs/os/dockerfiles

    scripts:
      directory: .local/envs/os/scripts

    data_config:
      files:
        - problem_file: .local/envs/os/data/dev.json
          script_dir: .local/envs/os/scripts/dev/
          index_prefix: "dev-001-"

      bk: [ ]
      ignore: [ ]

os-std:
  module: "src.server.tasks.os_interaction.OSInteraction"
  parameters:
    name: "os-std"
    concurrency: 24
    round_limit: 8

    docker_config:
      localhost: local-os
      directory: .local/envs/os/dockerfiles

    scripts:
      directory: .local/envs/os/scripts

    data_config:
      files:
        - problem_file: .local/envs/os/data/1/*.json
          script_dir: .local/envs/os/scripts/1/
          index_prefix: "std-001-"
        - problem_file: .local/envs/os/data/2/*.json
          script_dir: .local/envs/os/scripts/2/
          index_prefix: "std-002-"
        - problem_file: .local/envs/os/data/3/*.json
          script_dir: .local/envs/os/scripts/3/
          index_prefix: "std-003-"
        - problem_file: .local/envs/os/data/4/*.json
          script_dir: .local/envs/os/scripts/4/
          index_prefix: "std-004-"
        - problem_file: .local/envs/os/data/5/*.json
          script_dir: .local/envs/os/scripts/5/
          index_prefix: "std-005-"
        - problem_file: .local/envs/os/data/6/*.json
          script_dir: .local/envs/os/scripts/6/
          index_prefix: "std-006-"
        - problem_file: .local/envs/os/data/7/*.json
          script_dir: .local/envs/os/scripts/7/
          index_prefix: "std-007-"

      bk: [ ]
      ignore: [ ]
